import type { Metadata } from "next";
import "@/css/globals.css";

export const metadata: Metadata = {
  title: "Dashboard - Opcast",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        {children}  
    </>
  );
}
